### ISSUE TITLE
from_h5ad writes zero-valued data into the sparse X array

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SingleCell#12]
Create a new SOMA group using `from_h5ad` and a source dataset with a sparse X array.

The resulting TileDB X/data array will be sparse, but will contain zero valued data. Every coordinate (even those with zero value) is present in the resulting array.

**Comment by aaronwolen** [comment]
@bkmartinjr this should be resolved by #28 but I'll wait for your confirmation before closing.

**Comment by bkmartinjr** [comment]
Confirmed on a couple of test datasets. Thanks!
