### ISSUE TITLE
Investigate dimensioning of X/data and X/raw layers

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SingleCell#15]
For Seurat data, raw and process `X` data have the same dimensions. For some anndata files examined so far, sometimes they do not. It's our understanding that any layered matrices should share the same dimensions -- this constraint is satisfiable for Seurat-provenance data, yet not for anndata-provenance data. This is an opportunity for discussion.

**Comment by brianraymor** [comment]
I would recommend that we open issues against the soma specification if the implementation is blocked by ambiguity. 

To be fair, the model seems to be described in the most detail in the [ATAC/RNA multi-omics section](https://github.com/single-cell-data/matrix-api/blob/main/specification.md#rna) which would not be the first place that I might look.

### ATAC/RNA multi-omics

These experiments generate two data modalities from the same cells, and have separate filtering and analysis steps. These measure a subset of the same set of "gene" annotations, but might have a non-zero difference. So, they might produce the following X matrices (shapes in parentheses):

(m, n): RNA.raw

(o, p) RNA.filtered (some genes and cells masked)

(o, p) RNA.normalized (a transformation of RNA.filtered)

...

The above can be represented by the following:

* There will be a super-group containing four sc_groups:  RNA.raw, RNA.filtered, ATAC.normalized and ATAC.filtered
* Each group will have separate obs/var dataframes, and separate X arrays

### RNA

* RNA.raw - along with its unfiltered obs & var, will be represented as a sc_group with **m** observations and **n** variables. The RNA.raw X will be a TileDB array with a single attribute containing the RNA.raw layer.
* RNA.filtered & RNA.normalized are contained in a single sc_group with **o** observations and **p** variables. The filtered and normalized values can be either stored in a single array if they have the same coordinates, or as two arrays if they differ in which cells have a value.

In the above cases, it is most likely that the X arrays will be sparse.

**Comment by bkmartinjr** [comment]
Related issue:  `adata.raw.var` does not seem to be retained at all.  It may contain data _not_ in `adata.var`, so it needs to be persisted somewhere.

**Comment by ambrosejcarr** [comment]
We also identified a case where annotations are layer specific: The
cellxgene schema carries X_approximate_distribution and X_normalization,
both of which specify characteristics of the "X" layer.

In the case of individual datasets, these live in layer-specific uns, but
when multiple datasets are concatenated we may want to map them to a
categorical in obs.

**Comment by johnkerl** [comment]
Decided on today's call:

* For now we write `X` and `X_raw` as separate groups
* Each with their own `obs` and `var` -- so we will need `obs_raw` and `var_raw` for labels

cc @ambrosejcarr @bkmartinjr @brianraymor

**Comment by johnkerl** [comment]
This is addressed in the next-generation data model: https://github.com/single-cell-data/SOMA/blob/spec-revision/brainstorming.md
