### ISSUE TITLE
Test if a URI is a valid SOMA dataset

### ISSUE THREAD

**Issue by roaga** [single-cell-data/TileDB-SingleCell#163]
There currently isn't a strong way to check if a given URI is a valid SOMA dataset without first initializing a SOMA object. Additionally, `exists()` (which requires initializing a SOMA object first) only checks if the URI points to a TileDB group, not if it is specifically SOMA data.

**Comment by johnkerl** [comment]
As of https://github.com/single-cell-data/TileDB-SingleCell/pull/133 we have array-level/group-level metadata on SOCOs, SOMAs, and their components …

… however, getting at this currently from a URI requires either (a) instantiating a SOCO/SOMA object, or (b) dropping down to the tiledb (not tiledbsc) API -- this can be improved

**Comment by johnkerl** [comment]
Resolved by #175
