### ISSUE TITLE
from_h5ad_unless_exists() needs a `ctx` argument

### ISSUE THREAD

**Issue by aaronwolen** [single-cell-data/TileDB-SingleCell#229]

**Comment by johnkerl** [comment]
@aaronwolen `from_h5ad` also doesn't have a `ctx` argument -- what we've been doing is putting the `ctx` into the SOMA constructor e.g.

```
soma = tiledb.SOMA(uri, ctx=ctx)
tiledbsc.io.from_h5ad(soma, '/path/to/file.h5ad')
# or
tiledbsc.io.from_h5ad_unless_exists(soma, '/path/to/file.h5ad')
```

Perhaps we should add an optional `ctx` argument to all of the `tiledbsc.io.from_....`, which, if provided, would supersede the `ctx` (if any) from the SOMA constructor -- ?

**Comment by johnkerl** [comment]
I think what we need is https://github.com/single-cell-data/TileDB-SingleCell/pull/230

**Comment by aaronwolen** [comment]
Oh yeah, I like that approach.

**Comment by johnkerl** [comment]
@mdylan2 https://github.com/single-cell-data/TileDB-SingleCell/releases/tag/0.1.4
