### ISSUE TITLE
(edge case) Unreadable df in an obs slot

### ISSUE THREAD

**Issue by johnkerl** [single-cell-data/TileDB-SingleCell#38]
Input:

http://czi.bruce-public.s3.us-east-1.amazonaws.com/Single_cell_atlas_of_peripheral_immune_response_to_SARS_CoV_2_infection.h5ad

Ingest using our `ingestor.py`

```
obs=tiledb.open('obs')
obs.df[:]
  File "pyarrow/table.pxi", line 1834, in pyarrow.lib.Table.from_arrays
  File "pyarrow/table.pxi", line 1445, in pyarrow.lib.Table.validate
  File "pyarrow/error.pxi", line 99, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: Column 31 named ethnicity_ontology_term_id expected length 44721 but got length 0
```

**Comment by johnkerl** [comment]
@bkmartinjr can re refresh this link?
http://czi.bruce-public.s3.us-east-1.amazonaws.com/Single_cell_atlas_of_peripheral_immune_response_to_SARS_CoV_2_infection.h5ad

**Comment by bkmartinjr** [comment]
done

**Comment by johnkerl** [comment]
@bkmartinjr this file ingests successfully now with all our "type-diversity" mods in place 🎉
