### ISSUE TITLE
from_anndata converts very dense X array to sparse

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SingleCell#41]
The H5AD below contains a very dense X array (99.998% _dense_), but when it is ingested with `from_anndata()`, it is converted to a sparse TileDB array, increasing its size 3X (comparing compressed TileDB to _uncompressed_ H5AD).

Related to #40 

In this case, it seems clear that it should have created a dense array.

Sample (temporarily) at: http://czi.bruce-public.s3.us-east-1.amazonaws.com/soma_test/10x_pbmc68k_reduced.h5ad

**Comment by johnkerl** [comment]
@bkmartinjr I'm not sure what we can do here ...

* We are using string `obs_id`/`var_id` dimensions for `X`
* Dense arrays do not support dimension datatype 'STRING_ASCII'

**Comment by bkmartinjr** [comment]
Closing - this is confusion on my part, not a real issue.
