### ISSUE TITLE
non-float32 X data cast to float32 inappropriately

### ISSUE THREAD

**Issue by bkmartinjr** [single-cell-data/TileDB-SingleCell#42]
If you ingest an AnnData with a float64 X array, the resulting TileDB array will be float32.  This seems inappropriate - if the user had wanted single precision floats, they would have downcast the AnnData before conversion.

I do think there are rare cases where unsolicited up-casts are acceptable, eg, if the source data is float16, silently converting to float32 seems harmless. But silent loss of precision seems like an unreasonable step.

Similarly, non-floats are also cast to float32.  Also seems incorrect.

**Comment by johnkerl** [comment]
https://github.com/single-cell-data/TileDB-SingleCell/pull/53 is merged & all its `TODO: ... #42` are now un-TODO-ed and enabled in `apis/python/tests/`.
